services:
  backend:
    image: grabit-backend
    pull_policy: never
    container_name: grabit-backend
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    depends_on:
      - mysql
    ports:
      - 8443:8443

  mysql:
    image: mysql:8.0.40-debian
    container_name: grabit-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=grabit_db
    # ports:
    #   - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
