spring:
  application:
    name: grabit
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:test}
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  file:
    path: logs
    name: logs/grabit-${build.timestamp}.log
  logback:
    rollingpolicy:
      max-history: 20
      max-file-size: 100MB
