spring:
  datasource:
    url: ${PRODUCTION_DATABASE_URL}
  liquibase:
    enabled: true
    url: ${PRODUCTION_DATABASE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    '[com.grabit]': INFO

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: grabit_pwd
    key-password: grabit_pwd
    key-alias: grabit_cert
